name: 🚀 Build & publish FTP

env:
  CONFIGURATION: Release
  DOTNET_VERSION: '7.0.x'
  WORKING_DIRECTORY: 'Website/InfoTerraTerra/InfoTerraTerra'
  PUBLISHED_PACKAGE_PATH: 'Website/InfoTerraTerra/InfoTerraTerra/published/'
  
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Set up dependency caching for faster builds
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build

    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.PUBLISHED_PACKAGE_PATH }}"
    
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.PUBLISHED_PACKAGE_PATH }}
        
  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps: 
        - name: Download artifact from build job
          uses: actions/download-artifact@v3
          with:
            name: webapp
            path: ${{ env.PUBLISHED_PACKAGE_PATH }}
        - name: 📂 Deploy to SmarterASP.NET
          uses: jahbenjah/SmarterASP.NET-web-deploy@1.0.0
          with:
            website-name: fbonizzi-001-site1
            server-computer-name: https://win6047.site4now.net:8172/MsDeploy.axd?site=fbonizzi-001-site1
            server-username: fbonizzi-001
            server-password: ${{ secrets.ftp_password }}
            source-path: ${{ env.PUBLISHED_PACKAGE_PATH }}
            target-path: info-terra-terra/
            EnableMSDeployAppOffline: true
        - name: 📂 Sync files (FTP)
          uses: SamKirkland/FTP-Deploy-Action@v4.3.4
          with:
            local-dir: ${{ env.PUBLISHED_PACKAGE_PATH }}
            server-dir: info-terra-terra/
            server: win6047.site4now.net
            username: fbonizzi-001
            password: ${{ secrets.ftp_password }}
      
    
