name: 🚀 Build & publish SmarterAspNet

env:
  CONFIGURATION: Release
  DOTNET_VERSION: '7.0.x'
  WORKING_DIRECTORY: 'Website\InfoTerraTerra\InfoTerraTerra'
  PUBLISHED_PACKAGE_PATH: '\Website\InfoTerraTerra\InfoTerraTerra\publish'
  
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Set up dependency caching for faster builds
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build

    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.PUBLISHED_PACKAGE_PATH }}"

    - name: 📂 IIS Deploy
      uses: jahbenjah/SmarterASP.NET-web-deploy@1.0.0
      with:
        website-name: fbonizzi-001-site1
        server-computer-name: https://win6047.site4now.net:8172
        server-username: fbonizzi-001
        server-password: ${{ secrets.ftp_password }}
        source-path: '\Website\InfoTerraTerra\InfoTerraTerra\publish\
